apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-app
  labels:
    app: inventory-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-app
  template:
    metadata:
      labels:
        app: inventory-app
    
    spec:
      containers:
        - name: inventory-app
#          image: icr.io/appnamespace/app
          image: dhanusharch2/projectrepo:app
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          env:
            - name: DISABLE_WEB_APP
              value: "false"
